package com.drosa.efx.domain.model.finances;

public enum DataProvider {
	DUKASCOPY_FOREX,DUKASCOPY_FOREX2,DUKASCOPY_FOREX3,DUKASCOPY_FOREX4,PEPPERSTONE_FOREX,TRUEFX,FOREXDATA_FOREX,FOREXDATA_FOREX0,KIBOT,
	KIBOTES, DAVE,DAVEVOL, DAVEVOLMAXMIN
}
